export default [
  {
    show_title: 'Pulp Fiction',
    category: 'Oscar-winning Movies',
    release_year: '1994',
    poster: 'http://netflixroulette.net/api/posters/880640.jpg',
    runtime: '154 min',
    summary: 'Weaving together three stories featuring a burger-loving hit man, his philosophical partner and a washed-up boxer, Quentin Tarantino influenced a generation of filmmakers with this crime caper\'s stylized, over-the-top violence and dark comic spirit.',
    director: 'Quentin Tarantino',
    show_cast: 'John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis, Harvey Keitel, Tim Roth, Amanda Plummer, Ving Rhames, Eric Stoltz, Maria de Medeiros',
    rating: '4.1',
    show_id: 880640,
  },
  {
    show_title: 'Pulp Fiction',
    category: 'Oscar-winning Movies',
    release_year: '1994',
    poster: 'http://netflixroulette.net/api/posters/880640.jpg',
    runtime: '154 min',
    summary: 'Weaving together three stories featuring a burger-loving hit man, his philosophical partner and a washed-up boxer, Quentin Tarantino influenced a generation of filmmakers with this crime caper\'s stylized, over-the-top violence and dark comic spirit.',
    director: 'Quentin Tarantino',
    show_cast: 'John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis, Harvey Keitel, Tim Roth, Amanda Plummer, Ving Rhames, Eric Stoltz, Maria de Medeiros',
    rating: '4.1',
    show_id: 880641,
  },
  {
    show_title: 'Pulp Fiction',
    category: 'Oscar-winning Movies',
    release_year: '1994',
    poster: 'http://netflixroulette.net/api/posters/880640.jpg',
    runtime: '154 min',
    summary: 'Weaving together three stories featuring a burger-loving hit man, his philosophical partner and a washed-up boxer, Quentin Tarantino influenced a generation of filmmakers with this crime caper\'s stylized, over-the-top violence and dark comic spirit.',
    director: 'Quentin Tarantino',
    show_cast: 'John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis, Harvey Keitel, Tim Roth, Amanda Plummer, Ving Rhames, Eric Stoltz, Maria de Medeiros',
    rating: '4.1',
    show_id: 880642,
  },
  {
    show_title: 'Pulp Fiction',
    category: 'Oscar-winning Movies',
    release_year: '1994',
    poster: 'http://netflixroulette.net/api/posters/880640.jpg',
    runtime: '154 min',
    summary: 'Weaving together three stories featuring a burger-loving hit man, his philosophical partner and a washed-up boxer, Quentin Tarantino influenced a generation of filmmakers with this crime caper\'s stylized, over-the-top violence and dark comic spirit.',
    director: 'Quentin Tarantino',
    show_cast: 'John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis, Harvey Keitel, Tim Roth, Amanda Plummer, Ving Rhames, Eric Stoltz, Maria de Medeiros',
    rating: '4.1',
    show_id: 880643,
  },
  {
    show_title: 'Pulp Fiction',
    category: 'Oscar-winning Movies',
    release_year: '1994',
    poster: 'http://netflixroulette.net/api/posters/880640.jpg',
    runtime: '154 min',
    summary: 'Weaving together three stories featuring a burger-loving hit man, his philosophical partner and a washed-up boxer, Quentin Tarantino influenced a generation of filmmakers with this crime caper\'s stylized, over-the-top violence and dark comic spirit.',
    director: 'Quentin Tarantino',
    show_cast: 'John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis, Harvey Keitel, Tim Roth, Amanda Plummer, Ving Rhames, Eric Stoltz, Maria de Medeiros',
    rating: '4.1',
    show_id: 880644,
  },
  {
    show_title: 'Pulp Fiction',
    category: 'Oscar-winning Movies',
    release_year: '1994',
    poster: 'http://netflixroulette.net/api/posters/880640.jpg',
    runtime: '154 min',
    summary: 'Weaving together three stories featuring a burger-loving hit man, his philosophical partner and a washed-up boxer, Quentin Tarantino influenced a generation of filmmakers with this crime caper\'s stylized, over-the-top violence and dark comic spirit.',
    director: 'Quentin Tarantino',
    show_cast: 'John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis, Harvey Keitel, Tim Roth, Amanda Plummer, Ving Rhames, Eric Stoltz, Maria de Medeiros',
    rating: '4.1',
    show_id: 880645,
  },
  {
    show_title: 'Pulp Fiction',
    category: 'Oscar-winning Movies',
    release_year: '1994',
    poster: 'http://netflixroulette.net/api/posters/880640.jpg',
    runtime: '154 min',
    summary: 'Weaving together three stories featuring a burger-loving hit man, his philosophical partner and a washed-up boxer, Quentin Tarantino influenced a generation of filmmakers with this crime caper\'s stylized, over-the-top violence and dark comic spirit.',
    director: 'Quentin Tarantino',
    show_cast: 'John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis, Harvey Keitel, Tim Roth, Amanda Plummer, Ving Rhames, Eric Stoltz, Maria de Medeiros',
    rating: '4.1',
    show_id: 880647,
  },
];
