export default [
  {
    show_title: 'Pulp Fiction',
    category: 'Oscar-winning Movies',
    release_year: '1994',
    poster: 'http://netflixroulette.net/api/posters/880640.jpg',
    runtime: '154 min',
    summary: 'Weaving together three stories featuring a burger-loving hit man, his philosophical partner and a washed-up boxer, Quentin Tarantino influenced a generation of filmmakers with this crime caper\'s stylized, over-the-top violence and dark comic spirit.',
    director: 'Quentin Tarantino',
    show_cast: 'John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis, Harvey Keitel, Tim Roth, Amanda Plummer, Ving Rhames, Eric Stoltz, Maria de Medeiros',
    rating: '4.1',
    show_id: 880640,
  },
  {
    show_title: 'Kill Bill: Vol. 1',
    category: 'Action & Adventure',
    release_year: '2003',
    poster: 'http://netflixroulette.net/api/posters/60031236.jpg',
    runtime: '111 min',
    summary: 'An assassin is shot by her ruthless employer, Bill, and other members of their assassination circle. But she lives -- and plots her vengeance.',
    director: 'Quentin Tarantino',
    show_cast: 'Uma Thurman, Lucy Liu, Vivica A. Fox, Daryl Hannah, David Carradine, Michael Madsen, Julie Dreyfus, Chiaki Kuriyama, Sonny Chiba, Gordon Liu',
    rating: '3.8',
    show_id: 60031236,
  },
  {
    show_title: 'Kill Bill: Vol. 2',
    category: 'Action & Adventure',
    release_year: '2004',
    poster: 'http://netflixroulette.net/api/posters/60032563.jpg',
    runtime: '137 min',
    summary: 'The Bride has three left on her rampage list: Budd, Elle Driver and Bill himself. But when she arrives at Bill\'s house, she\'s in for a surprise.',
    director: 'Quentin Tarantino',
    show_cast: 'Uma Thurman, David Carradine, Michael Madsen, Daryl Hannah, Gordon Liu, Michael Parks, Perla Haney-Jardine, Helen Kim, Claire Smithies, Clark Middleton',
    rating: '3.8',
    show_id: 60032563,
  },
  {
    show_title: 'Jackie Brown',
    category: 'Dramas',
    release_year: '1997',
    poster: 'http://netflixroulette.net/api/posters/60010514.jpg',
    runtime: '154 min',
    summary: 'Jackie Brown is an aging flight attendant who smuggles cash on the side. But when she\'s busted and pressured to help with an investigation, she plans to play the opposing forces against each other and walk away with the dough.',
    director: 'Quentin Tarantino',
    show_cast: 'Pam Grier, Samuel L. Jackson, Robert Forster, Bridget Fonda, Michael Keaton, Robert De Niro, Michael Bowen, Chris Tucker, Lisa Gay Hamilton, Tommy \'Tiny\' Lister',
    rating: '3.7',
    show_id: 60010514,
  },
  {
    show_title: 'Reservoir Dogs',
    category: 'Independent Movies',
    release_year: '1992',
    poster: 'http://netflixroulette.net/api/posters/902003.jpg',
    runtime: '99 min',
    summary: 'Quentin Tarantino\'s directorial debut is raw, violent, often mimicked -- and unforgettable. A botched robbery indicates a police informant, and the pressure mounts in the aftermath at a warehouse. Crime begets violence as the survivors unravel.',
    director: 'Quentin Tarantino',
    show_cast: 'Harvey Keitel, Tim Roth, Michael Madsen, Steve Buscemi, Chris Penn, Lawrence Tierney, Edward Bunker, Quentin Tarantino, Randy Brooks, Kirk Baltz',
    rating: '4.0',
    show_id: 902003,
  },
  {
    show_title: 'Four Rooms',
    category: 'Comedies',
    release_year: '1995',
    poster: 'http://netflixroulette.net/api/posters/520179.jpg',
    runtime: '98 min',
    summary: 'Weaving together three stories featuring a burger-loving hit man, his philosophical partner and a washed-up boxer, Quentin Tarantino influenced a generation of filmmakers with this crime caper\'s stylized, over-the-top violence and dark comic spirit.',
    director: 'Quentin Tarantino',
    show_cast: 'John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis, Harvey Keitel, Tim Roth, Amanda Plummer, Ving Rhames, Eric Stoltz, Maria de Medeiros',
    rating: '3.6',
    show_id: 520179,
  },
  {
    show_title: 'Django Unchained',
    category: 'Dramas',
    release_year: '2012',
    poster: 'http://netflixroulette.net/api/posters/70230640.jpg',
    runtime: '154 min',
    summary: 'Accompanied by a German bounty hunter, a freed slave named Django travels across America to free his wife from a sadistic plantation owner.',
    director: 'Quentin Tarantino',
    show_cast: 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington, Samuel L. Jackson, Walton Goggins, Dennis Christopher, James Remar, Michael Parks, Don Johnson',
    rating: '4.0',
    show_id: 70230640,
  },
];
